### ISSUE TITLE
Enhancement: range finder input

### ISSUE THREAD

**Issue by sthgrau** [gcormier/megadesk#10]
In between seeing the link to this project in HN to being able to see it, I thought about the possibility of using range finders to set the height.

Basic idea:
- You press a button (so it doesn't change by accident)
- Then place your hand above or below a range finder (2 most likely needed)
- The microcontroller then calculates the delta and changes to that height. I guess that for lowering, it would need to be a little lower since you are measuring the top of the hand vs where you want it.

The main benefit of this is you can act naturally and place your arm as it feels comfortable, and be able to do that in one momentary action.

Thanks for making the project.

**Comment by gcormier** [comment]
It would definitely be possible - you have the current position known in the code, and you can offset it in either direction based on code from your range finder! The only caveat would be how to talk to the sensors.

Perhaps a fun idea, make the sensors talk on the LIN bus :)
