### ISSUE TITLE
Problem storing height settings

### ISSUE THREAD

**Issue by gtudan** [gcormier/megadesk#105]
Hi Greg! I recently got a mega desk from tindie, but it's giving me a hard time setting it up.

The basics seem to work fine - the desk moves up and down and even the motor calibration works. But when I try to store any of the settings, one of the following things happen:

- it will beep just fine and become unresponsive until powercycled
- it reboots (startup tones playing)
- it hangs, playing a continuous very low tone until power cycled

I already tried factory resetting it and recalibrating the motor. I'm not quiet sure what's going on - any hint would be highly appreciated! Could this be a hardware issue - maybe a faulty eeprom?

**Comment by gcormier** [comment]
Hmm that's odd behaviour. Can you reach out to me via Tindie with your order number and we can get that sorted out.
