### ISSUE TITLE
ATTiny1624 Support

### ISSUE THREAD

**Issue by gcormier** [gcormier/megadesk#107]
ATTINY1624 branch up in case the availability (or pricing) of this becomes better then ATTINY841.

Pros
- Two hardware serial
- Might be cheaper?

Cons
- UPDI programmers less prevalent

Need to work on code.

- [x] Only 256b EEPROM available instead of 512b - fix up initialize
- [x] Frequency issues
- [x]  Hardware serial for 2nd serial port

**Comment by gcormier** [comment]
@philwmcdonald Unsure if any of the optimizations you made are related, I've only just flashed the first test and noticed the pitch is higher on the startup tone. Later this week I'll poke around. I'll probably just also flash a 4 line program that outputs a given frequency tone and measure it with the scope to see if it's something at the core of my configuration.

**Comment by gcormier** [comment]
Woops, I thought I read the fuses set the default clock to 16MHz. The 1624 runs at 20MHz by default. A fuse change gets us at 16MHz to save a bit of power.

**Comment by gcormier** [comment]
![image](https://user-images.githubusercontent.com/8388983/187329649-cdbee0c6-22dd-413c-be11-34d7cd457d20.png)

Serial oddities on LIN bus. Top is 1624, bottom is tiny841. No code changes. 1624 is not pulling low for 775uSec.

**Comment by philwmcdonald** [comment]
Lin::serialBreak() likely doesn't play nice with hardware serial. it delays for:
breakTime = LIN_BREAK_DURATION*TBIT; // 780us break time
May need a different approach...

It's also possible txPin passed into the constructor isn't correct, or that serialBreak() requires:
pinMode(txPin, OUTPUT);

**Comment by philwmcdonald** [comment]
Never found a need for all that eeprom previously.
You could just initialize/use 256b instead without any impact to the operation of megadesk.

**Comment by gcormier** [comment]
Bingo, setting pinMode fixed it!

**Comment by gcormier** [comment]
Serial working well on 1624

![image](https://user-images.githubusercontent.com/8388983/189495630-4cc73562-7f3d-455b-9b7b-45d605d2af03.png)

**Comment by gcormier** [comment]
Tested build against attin841, fixed some issues. Working!
