### ISSUE TITLE
Can megadesk control more than two legs, or link up with multiple controllers?

### ISSUE THREAD

**Issue by gritstub** [gcormier/megadesk#109]
Hi, I had asked via Tindie, but not sure if the message form was sent properly.

I have two complete sets of Bekant standing desks that I would like to join together with either 3 or 4 legs to raise/lower one very large desk.  Would one (or even two) Megadesk controller allow for this functionality?

I tried with just 1 leg, and also daisy chaining 3 legs with a standard Bekant controller, but it refuses to move up/down when setup this way.

**Comment by gcormier** [comment]
Please check out https://github.com/gcormier/megadesk/discussions/55
