### ISSUE TITLE
Bluetooth LE support

### ISSUE THREAD

**Issue by jeamland** [gcormier/megadesk#11]
Is there room on the board for a Bluetooth LE module? I'd cheerfully write an app to control it if there were...

**Comment by jottr** [comment]
Some people on HN already suggested to use an ESP8266 instead.   
@gcormier what are your thoughts about this?   
Generally, some kind of networking stack, BLE or 802.11, would be very useful.

**Comment by gcormier** [comment]
The main issue would be the physical size. The board space required for an ESP is quite big. Once I get the rush of orders sorted out I can take a look at board layout, but I don't think it's promising. Not only are we constrained in the X/Y, but also height - there are a few sections of the case that have ribs running across which limit where we can place taller components. I'm note sure if the ESP's height is slim enough to span those sections. Of course, snipping them away might be an option in some areas, would need more research!

**Comment by gcormier** [comment]
![image](https://user-images.githubusercontent.com/8388983/51952803-d34e3600-2407-11e9-8339-ba371b94ceaa.png)

This is what you're up against trying to get an ESP32 in there.

**Comment by jeamland** [comment]
The hatched area is the problem? (I'm not sure how to read this image.)

**Comment by gcormier** [comment]
Well, that area is a keep out area, but that shouldn't be an issue.

Still, the overall size of the module doesn't leave very much room for other components.

Also, you can see the grey horizontal lines which mark the plastic ribs of the case. The deep component area is where there is more room, but the other parts can't be very deep.

You'd have to spend some time trying to do the routing in KiCad do see if it's doable :)

**Comment by jeamland** [comment]
Is there a BTLE module that could be added to the existing design? Would that cause less issues?

**Comment by jottr** [comment]
I'm confused. The ESP8266 comes in many different form factors. [This one](https://www.adafruit.com/product/2491) should fit the enclosure easily, no? 
Personally, I wouldn't care if the ESP would stick out of the enclosure, or even be outside of it in it's own small case.

**Comment by jottr** [comment]
Actually, why do you constrain yourself with the original enclosure in the first place? Wouldn't it be nice to have room to host an LCD which could display the height and settings stored in memory? 
Also, additional buttons could be useful to improve UX.

**Comment by jeamland** [comment]
I'm fine with staying in the footprint of the original enclosure as that means less mucking around with extra parts. If I had BLE or WiFi then I could get my computer to display that stuff.

**Comment by gcormier** [comment]
@jottr The ESP8266 sizing is more or less the same.

![image](https://user-images.githubusercontent.com/8388983/51983943-0a543400-2468-11e9-98e0-b327e7c45cee.png)

As mentioned in the readme, I didn't want a hacky looking enclosure that was 3D printed with ugly buttons. Getting custom membrane buttons is very expensive.
