### ISSUE TITLE
Megadesk does not work with newer ATTinyCore versions

### ISSUE THREAD

**Issue by gcormier** [gcormier/megadesk#13]
Newer ATTinyCore breaks megadesk. Need to investigate.

Fow now, stick to ATTinyCore 1.1.5.

**Comment by SpenceKonde** [comment]
This was an ATTinyCore bug. It was introduced in 1.2.2, and is fixed in 1.2.3, which should be available on board manager within a few days.

**Comment by gcormier** [comment]
Resolved using 1.2.3
