### ISSUE TITLE
Cable Support needed - Colors

### ISSUE THREAD

**Issue by ghost** [gcormier/megadesk#135]
Hello!
Just a short question, I try to use the original power supply with your customized board. 

The original board seems to have following colors (see attachment): 
blue, white, red

Your customized board and cable comes with following colors (see attachment): 
red, black, yellow

Can you provide a mapping, so that I know, which color of the original board belongs to your used color scheme? I assume, red is red? ;)

![IKEA](https://github.com/gcormier/megadesk/assets/133763508/248655c4-bab4-4714-b459-5f278a1c1585)

Thanks for your help.

**Comment by gcormier** [comment]
For the IKEA PCB, https://github.com/gcormier/megadesk/blob/master/DIY.md
`Red is positive (24VDC), white is negative, blue is LIN.`

For the megadesk cable
Red=Red
White=Black
Blue=Yellow
