### ISSUE TITLE
Doc Enhancement: Explain how to use HTTP requests to control the desk via the companion

### ISSUE THREAD

**Issue by mimre25** [gcormier/megadesk#159]
I'm one of those smart ones that cut one of the ribbon cables while trying to open up the controller "box". 
Luckily, I've also bought the companion and can use it to control the desk.

I have absolutely no experience with an esp32 or any similar boards. 
However, I've noticed that the companion is running a webserver and so I just "spied" on the requests that are used.
This way I could figure out how to automate things via HTTP.

My suggestion is to add a section/document detailing how to use HTTP to control the desk via the companion.

I'm happy to contribute such a "how-to" if desired :slightly_smiling_face: 
Let me know if you want to have that!

**Comment by gcormier** [comment]
Sure, if you are willing to submit a PR we can add it. This will be simple REST/HTTP calls to the esphome rest API.

It could be added to the bottom of https://github.com/gcormier/megadesk_companion/blob/main/readme.md

**Comment by mimre25** [comment]
PR is hover there: https://github.com/gcormier/megadesk_companion/pull/5 :slightly_smiling_face:
