### ISSUE TITLE
Doesn't stop beeping during and after moving to preset location

### ISSUE THREAD

**Issue by petemill** [gcormier/megadesk#163]
When choosing a preset location, during movement and only if the movement lasts for more than ~1 second, the megadesk will start beeping continuously. It moves to the preset location perfectly, but it doesn't stop beeping continuously even after reaching the location. Only way to stop the beeping is to move the desk down. Moving the desk up does not stop the beeping.

**Comment by petemill** [comment]
This issue does not present when disabling audio feedback mode. The issue comes back when re-enabling audio feedback mode.

**Comment by gcormier** [comment]
Super odd, can you post a video of the behavior?

Do you have the hardware to re-flash the firmware?
