### ISSUE TITLE
ECS+ Support Workaround

### ISSUE THREAD

**Issue by martenmatrix** [gcormier/megadesk#165]
Do ROL ERGO ECS+ Controllers work with the fully assembled PCB?
![image](https://github.com/gcormier/megadesk/assets/76761713/a8d051f8-71d2-4c74-a0eb-90edbcaeccf1)
It seems that the inputs and outputs are the same, however there is currently no PCB in between, which I could replace. Would it work to just solder the three outgoing pins of Megadesks PCB with the cables and to attach the "3-stripe thing" to the PCBs correct ingoing ports?

**Comment by gcormier** [comment]
Can you get more information on whatever that plugs in to?

**Comment by martenmatrix** [comment]
Thanks for the quick reply. Of course!

![image](https://github.com/gcormier/megadesk/assets/76761713/e53eab2c-171d-4e34-b82f-a5d24beee3ff)
![image](https://github.com/gcormier/megadesk/assets/76761713/a2bcf78a-53f4-4a39-a8d1-ed5c9601476e)
![image](https://github.com/gcormier/megadesk/assets/76761713/44983baf-2b3f-4ae1-951c-1dbf4673f6b3)
![image](https://github.com/gcormier/megadesk/assets/76761713/ad8031d0-e2fd-4adb-b328-3392d39efe0c)
![image](https://github.com/gcormier/megadesk/assets/76761713/badc7c33-b9b7-4339-ac8a-4d18f22ff12e)
![image](https://github.com/gcormier/megadesk/assets/76761713/6a4dfb52-5b3b-4af7-851d-6a18eec6f476)

I hope that's enough information! :)

**Comment by gcormier** [comment]
What is the model of desk? Not clear as to why there is a 4 pin connector
when there's just 3 wires

**Comment by martenmatrix** [comment]
I was baffled by that aswell. The model name is on that silver sticker in one of the pictures, it's **GF-470**. However, I'm currently unable to find it online, bought it ~3 years ago. The only thing I can send you is [the manual](https://hta.hettich.com/fileadmin/Hettich_Technical_Assistant/PDFs/2019_10_29_Anleitung_Change_Top_Eco_EN_DE.pdf).

**Comment by gcormier** [comment]
I don't think it's compatible. This looks like the RODULF a bit, and it's likely if you open up that box, you'll find some high powered MOSFET's and it's actually sending the current to the motors instead of a signal via LIN bus.

**Comment by martenmatrix** [comment]
That's unfortunate :(. However, thank you so much for replying so quickly!
