### ISSUE TITLE
brand new megadeek keeps beeping 

### ISSUE THREAD

**Issue by acuszka** [gcormier/megadesk#170]
Hi,

I just received my Megadesk. I connected it, but it keeps beeping constantly and nothing else works (I think it keeps rebooting?). 

When in button test mode, the buttons work and beep when I press up and down. I have big desk manufactured 2021-46.

- I power cycled the desk multiple times
- I disconnected and connected everything multiple times
- I connected original controller and everything works
- My multimeter beeps for the red, black, and yellow wires

I'm not sure what to do next.

Video: [https://www.youtube.com/watch?v=u6QHKhnVBZ](https://www.youtube.com/watch?v=u6QHKhnVBZI)

![20240716_144204](https://github.com/user-attachments/assets/ab41494c-8d50-4ba1-8406-c76569524034)

![20240716_142600](https://github.com/user-attachments/assets/768f7842-ac5b-47a1-82e9-63b9cfb2d160)

![20240716_144845](https://github.com/user-attachments/assets/090df751-a118-49d3-a465-7fbc03365146)

**Comment by gcormier** [comment]
Hmm, I wonder if there was simply shipping damage. Looping indicates it cannot establish communication with the motors. Can your reach out to me via Tindie store so I can look at your order #?
