### ISSUE TITLE
BEKANT Power Supply Voltage

### ISSUE THREAD

**Issue by James-TR** [gcormier/megadesk#2]
As you have noticed, the BEKANT power supply delivers 24V at idle (no load), which is under the name-plate voltage. The voltage increases to 35V as soon as a resistive load such as the motors is put across the power supply.

Would need to spec components to handle the increased voltage whilst the desk is moving. The gradual increase in voltage is apparently responsible for the soft-start.

**Comment by gcormier** [comment]
The regulators I bought are good for input voltage up to 35v, although it might be worth it to look at a simple buck converter... 

I'll confirm the behavior on my side and make a note.

**Comment by gcormier** [comment]
Confirmed this behaviour. It takes about 6 seconds for the voltage to return from 35V to 24V after being idle.

I don't think it's responsible for any soft start/stop though, as it takes quite some time for the voltage to return back to 24V. So a second operation would run at 35V if it was nearly immediately after.

**Comment by gcormier** [comment]
b63923b7e8339dc6f86580f9c62a1275d52c6570 references the issue with voltage for now. I've opened issue #4  to look into it further.

**Comment by James-TR** [comment]
Thanks, it does seem interesting that they're overdriving the 24V motors at 35V... This may just be to get the extra speed.
