### ISSUE TITLE
IDÅSEN support

### ISSUE THREAD

**Issue by gcormier** [gcormier/megadesk#21]
Ikea has released a new motorized standing desk, the IDÅSEN.

Please thumbs-up this issue if support for that desk is of interest to you. It would require me investing in the purchase of a desk to reverse engineer, so there's significant costs to doing so.

**Comment by leoluk** [comment]
The new desk has bluetooth support, so it's probably easier to reverse engineer that.

**Comment by gcormier** [comment]
Ah interesting. This would very much be a software project I imagine, rather than hardware.

**Comment by HikariMisako** [comment]
Some comments on reddit suggest that the Linak DPG1C controller is a plug and play option that adds memory and a display for the Idasen. Even a review of the controller on Amazon suggests the same thing, so while it's more expensive at 100$ it could be a solution for people hoping to upgrade their Idasen desk.
