### ISSUE TITLE
Feature request: scheduling

### ISSUE THREAD

**Issue by bramjoosten** [gcormier/megadesk#27]
Hi guys, I'm having a specific use case that I want to drop here. Is the controller able to do this?

_As a lazy programmer with back pains, I would like to have the desk force me to stand up regularly, so I can stretch my body and live a healthier life._
 
I'm thinking every hour for 3 minutes, but It would need some trial and error. Ideally I want to have this happen to me only on working hours.

**Comment by gcormier** [comment]
#12 would be what you could target for this. The current megadesk has no clock. So likely you'd want to control it via serial to handle these types of automation, perhaps in Home Assistant and then the megadesk remains fairly ignorant to what's going on and merely thinks it's a position recall being triggered. I know of at least 2 people who've talked to me about serial comms via email but I don't think they are on GitHub yet.
