### ISSUE TITLE
Since I don't have a tindie-account I am going to hijack the GitHub project

### ISSUE THREAD

**Issue by grasegger** [gcormier/megadesk#29]
Ok, sorry for talking about the product here, but I don't want to create an account there until I know if I buy. 

I have zero knowledge about embedded programming, soldering and putting together cables aside from plugging in a power supply. 😓 

On the product page (https://www.tindie.com/products/gcormier/megadesk/) you talk about ordering a premade cable, which I can't find in your shop. As far as I can tell "connecting the cables" is soldering the cables to the correct contacts? I am a bit lost here tbh.

**Comment by gcormier** [comment]
No problem :) sorry about the confusion.

The product includes everything you need now. Previously, it was possible
to order just the board for those wanting to save a few bucks and use the
existing cable. I had zero people choose this path so now it's the board
and cable. I will update the docs next week to reflect that :)

**Comment by grasegger** [comment]
@gcormier Thanks, just ordered 👍
