### ISSUE TITLE
What can be used as keypads?

### ISSUE THREAD

**Issue by sichacvah** [gcormier/megadesk#34]
What can be used as keypads?

Hello! First of all thanks for that project! I was buy old bekant table  without controller recently and want to use our megadesk for it, but i don't know where and what keypads i can buy for it? Could you provide any tips for me?

**Comment by gcormier** [comment]
So the up/down buttons are merely SPST which connects the respective pins to ground over the ribbon cable.

I do have a breakout board design which you can see in the testing video

![image](https://user-images.githubusercontent.com/8388983/103414608-abfcc800-4b4c-11eb-9e25-6d680aeb48f7.png)

You could use the breakout pins to connect any buttons to them via soldering. Or, you could mount the 2 buttons as shown, and 3d print an enclosure.

As for something pre-made, off the shelf, I am not sure what options there are - this is why I designed megadesk to use the existing case as I didn't want to deal with designing a case and 3D printing it. 

You could use something like this

![image](https://user-images.githubusercontent.com/8388983/103414678-ee260980-4b4c-11eb-91c0-64fab9304b36.png)

Connected to the pin headers of the breakout board. (Only 2 of the buttons would work though)

**Comment by gcormier** [comment]
Oh they do sell a 2-button version as well.

![image](https://user-images.githubusercontent.com/8388983/103414740-36452c00-4b4d-11eb-8ba9-468347736213.png)

You could even just use adhesive tape or glue to put this on the front of a piece of wood and hide the circuit board behind it.

**Comment by codingforfun** [comment]
I used a physical 2 way momentary switch.
![PXL_20220119_162002606~2](https://user-images.githubusercontent.com/1388003/150172642-bae486da-b658-420e-8127-6e0ec7607e87.jpg)

**Comment by codingforfun** [comment]
Switched back to physical buttons after a while. The 2 way momentary switch was physically not stable enough for the clicking and got stuck over time. 

![Image](https://github.com/user-attachments/assets/dff83591-84f6-4444-b7c0-01c0f510bde0)
