### ISSUE TITLE
Ghost movement if SERIALCOMMS enabled

### ISSUE THREAD

**Issue by rhannink** [gcormier/megadesk#60]
Hello,

I build the firmware with the SERIALCOMMS enabled. I flashed it in my megadesk and it all seems working ok.
But once or twice every day the desk moves by itself to either the highest or the lowest position. This can be dangerous if eg the seat is under the desk.

I rebuild the firmware again, now without the serialcomms enabled and flashed it again and then everything is fine.

I have a 50 cm 3 Wireless cable connected to the RX/TX and GND and it is not yet connected to anything, might this be the problem?

Gr. Remco

**Comment by gcormier** [comment]
I think there is another name for that cable... it's an antenna :)

I would suggest disconnecting the cable to see if the phantom movements stop. I had the serialcomm enabled on mine for a few weeks (no cable attached) to verffy stability before merging it and had no phantom movements.
