### ISSUE TITLE
Change ICSP header

### ISSUE THREAD

**Issue by tagno25** [gcormier/megadesk#65]
I would recommend changing out the straight ICSP for a right angle header.

If the header is a right angle then it is possible to cut a hole in the back of the existing case, which allows a cable to easily connected and disconnected without disassembly. It didn't seem to interfere with the case if you don't cut a hole.

**Comment by gcormier** [comment]
Is there an action needed here? Changing BOM/notes? Is the current layout OK?

**Comment by tagno25** [comment]
I think the current layout is OK.  

I don't recall if the boards came with a header already populated at this point.  If they don't then just changing the DigiKey link in the DIY.md file would probably be sufficient.

https://www.digikey.ca/en/products/detail/amphenol-icc-fci/68459-406HLF/5359607

**Comment by philwmcdonald** [comment]
> I would recommend changing out the straight ICSP for a right angle header.
> 
> If the header is a right angle then it is possible to cut a hole in the back of the existing case, which allows a cable to easily connected and disconnected without disassembly. It didn't seem to interfere with the case if you don't cut a hole.

I did exactly this with the rev4 board. The pins extend out the back of the case. I can keep them covered with a socket or plug in serial or the avr programmer. I didn't have the part you reference, instead I bodged/soldered right-angle and straight header pins.

**Comment by philwmcdonald** [comment]
![IMG_20210520_001246331](https://user-images.githubusercontent.com/83505325/120042170-94304f80-bfd7-11eb-9265-e16fbcf10b48.jpg)

**Comment by gcormier** [comment]
a287e9a
