### ISSUE TITLE
Spare boards/parts

### ISSUE THREAD

**Issue by gcormier** [gcormier/megadesk#8]
I have enough parts for two units if anyone is interested - assembled or non.

**Comment by APINAPOIKAMIES** [comment]
How much $ for one?

**Comment by gcormier** [comment]
For the parts and PCB I'd say 15$ + shipping? Un-assembled.

**Comment by rpmoore16** [comment]
Do you still have any parts? I'm interested in purchasing one unit un-assembled.

**Comment by gcormier** [comment]
I do have 1 set left! Let me know your email address and we can work out the details.

**Comment by gcormier** [comment]
Still have one set available!

**Comment by rodcleveland** [comment]
I am interested in one assembled. Drop me an email, the address is on my profile. Thanks!

**Comment by AlexRoss-xx** [comment]
Is it still availible?

**Comment by gcormier** [comment]
The last one is reserved for @rodcleveland, but I am thinking of putting these up for sale on tindie since there seems to be some demand! Is that something you would be interested in?

**Comment by AlexRoss-xx** [comment]
yes. because it is impossible to buy some components in my country.

**Comment by gcormier** [comment]
@AlexRoss-xx Hi Alex - please send me your email and we can discuss.

**Comment by AlexRoss-xx** [comment]
Hi  Greg,  rasskazoff@gmail.com

**Comment by gcormier** [comment]
The spare boards are gone. I've ordered a new set of boards and parts and will be selling them via Tindie. https://www.tindie.com/products/gcormier/megadesk/

**Comment by GeeWizWow** [comment]
Hey. Tindie is having a moment, won't accept e-mail addresses or quantities. I'd love to pick one up un-assembled

**Comment by gcormier** [comment]
I've thought a bit about a parts-only version, but I"m unsure how to do it.. the capacitors are unmarked and would pose an issue... although, I could probably just dab them with a marker as there are only 3 different values.

I should have the last part (FPC header) in a week or two, then I can update the stock there and I'll try to rig up an parts-only option.

**Comment by GeeWizWow** [comment]
Most places ship them in a little baggie with the value written on the bag with a sharpie / sticker or something. (Happy to skip the headers, have more than enough here)

**Comment by gcormier** [comment]
Hmm a sticker with the part stuck on it as well might work. Even baggies would just be too big, and wasteful - these things are tiny! :)

**Comment by GeeWizWow** [comment]
masking tape ftw

**Comment by gcormier** [comment]
Good point! :) I'll post here when I get it up and running. Yeah I figure the kit would not come with pin headers - if someone doesn't already own hundreds of them... not a good sign for flashing it or assembly it successfully! :)

**Comment by gcormier** [comment]
Parts in stock!

https://www.tindie.com/products/gcormier/megadesk/

**Comment by GeeWizWow** [comment]
Picked one up, thanks Greg
