### ISSUE TITLE
I'm tall. When the table is goes to the upper limit no presets seem to respond.

### ISSUE THREAD

**Issue by frankhommers** [gcormier/megadesk#81]
See subject ;-)

When I unplug the the power cord it and re-plug it it starts to work again.

Also I found a workaround by just stopping underneath the upper limit.

Is this a known bug?

**Comment by gcormier** [comment]
Okay so just to be clear, you have a memory stored which is as high as the table will go? And once you recall this memory it will no longer move?

**Comment by frankhommers** [comment]
No when I move the table to the upper limit, and I recall a preset (of course below that level)  it does not work.

**Comment by philwmcdonald** [comment]
I tried to reproduce on most recent s/w on dev branch and couldn't.
Lots of changes were made w.r.t limits and some fixes to idle-states which previously required power-cycle to recover. I'm not convinced these would fix what you're seeing, but who knows. 
What version of the software do you have?

**Comment by frankhommers** [comment]
I'll post back to you when I flashed it. I am not sure atm. I am waiting for my AVR programmer to arrive.

**Comment by frankhommers** [comment]
I still have this with v2021.09-serial.hex. It's not a really big problem because I use a preset just below the top position.

**Comment by philwmcdonald** [comment]
I made some changes in my fork (which may not yet be ready for primetime):
https://github.com/philwmcdonald/megadesk/tree/dev
If you build the dev branch, with 
#define SERIALCOMMS
#define HUMANSERIAL
#define SERIALECHO
#define SERIALERRORS

If you still have the issue, then see if you can get serial connected/working I can look at the logs.

**Comment by frankhommers** [comment]
It's kind of hard to debug for me now, since I (hard) wired the megadesk to my Wemos D1. So I can't really test this now 😒

**Comment by gcormier** [comment]
I couldn't repro this on my desk :(

**Comment by gcormier** [comment]
Closing since we can't repro not does it seem like more info is coming.
