### ISSUE TITLE
Precompiled versions

### ISSUE THREAD

**Issue by frankhommers** [gcormier/megadesk#82]
I have my megadesk working, I just ordered an AVR programmer, so I can get started to send serial commands.

Would it be possible to also release the compiled .HEX files for ease of use?

**Comment by gcormier** [comment]
Hey Frank! Absolutely, I have been busy lately but meaning to tag a new stable release and publish the associated HEX file for easy flashing. I will try to get something put up this week!

**Comment by frankhommers** [comment]
That would be great! Save me the setup of yet another compilation environment ;-)

**Comment by gcormier** [comment]
https://github.com/gcormier/megadesk/releases/tag/v2021.09

Done!

**Comment by frankhommers** [comment]
Cool! I'll use 'em once my AVR programmer arrives!
