### ISSUE TITLE
Board seems to keep restarting

### ISSUE THREAD

**Issue by JorritPosthuma** [gcormier/megadesk#84]
Hi! First of all, thank you so much for the project. It's been working like a charm as a smarter replacement for the IKEA version. I also wanted to make it even smarter by connecting it to an ESP32 with Apple Homekit :), but I've ran in to some problems:

- When I connect the board to the SparkFun AVR programmer, it keep repeating the "BOOT" beeps every 2 seconds. However, I was able to flash the firmware with the Serial feature enabled
- When I connect it to the ESP32 it does the same, and I keep receiving `*E0,2` over serial (also repeating every 2 seconds), and it's not responding to any commands
- When it gets its power from the desk though, everything (still) works as expected

Do you have any idea what I could have done wrong? It might be my soldering skills as I'm still relatively new to the hobby of electronics :).

**Comment by gcormier** [comment]
It is unable to talk to the motors, so it resets itself. This is to be expected when programming and not attached to the desk. There is an option that will disable this reset.

For the ESP32, this is when everything is connected?

**Comment by JorritPosthuma** [comment]
Thanks for the quick reply! That makes sense :). I had everything connected with the ESP32 powered by the 5V of the pinouts of the board, but some components got hot pretty quickly, so that's probably not the right way to connect everything up 😅. 

A little outside of the scope of my original question, but could you suggest how you would power the ESP32? I imagined that with 2 different power supplies (the desk for the megadesk board, and a separate 5V PS for the ESP32) that would only lead to trouble? Or is that ok if you connect the grounds? (Sorry for the basic electronics questions 😅)

**Comment by gcormier** [comment]
Please check issue #83 - no you can't use the megadesk power.

A simple buck converter from Amazon to go from 24V to 5V would work.

**Comment by JorritPosthuma** [comment]
Thanks! I’ll do some more reading ☺️. Have a nice day!
