### ISSUE TITLE
Serial response garbled

### ISSUE THREAD

**Issue by frankhommers** [gcormier/megadesk#85]
I have flashed the latest `v2021.09-serial.hex` file. The serial commands DO work! Which is great!

But I get a "garbled" response on serial commands.

![image](https://user-images.githubusercontent.com/7355878/136109448-53ea4d14-d13e-43de-8b3d-e7c5d0c74388.png)
Above screenshot was take just after a `<T3000,255.` command.

These are my settings:
![image](https://user-images.githubusercontent.com/7355878/136109336-fb35904d-3c41-4552-9604-7c3a8a31395c.png)
Are they wrong?

Also it would be nice if the baudrate, databits, stopbits, parity and flow control were mentioned in the documentation.

**Comment by frankhommers** [comment]
I just tested this with different USB to Serial converters, on different PC's. Same result.

**Comment by gcormier** [comment]
115200 is indeed the correct speed. You could try reducing the speed in the code and your TTY to match in case there is some sort of interference? Have you tried the serial adapter with other devices?

**Comment by frankhommers** [comment]
I directly connected it to my Wemos and it disappeared... Very weird. I tried 3 different types of USB RS232 adapters and 2 PC's
