### ISSUE TITLE
Best controller for serial control?

### ISSUE THREAD

**Issue by DJPoulter** [gcormier/megadesk#86]
Reading through #12 I couldn't seem to find the best solution to this so asking it here. But what are peoples recommendations on a controller for serial control? I was thinking of just using a D1 mini. 

And then to follow it up would the best solution be to run connect the 3 pins from the programming header and run the cable out to the controller? Or has someone worked out a way to get power and fit a controller in the box itself?

**Comment by gcormier** [comment]
converting to Discussion
