### ISSUE TITLE
Audio feedback when not doing anything?

### ISSUE THREAD

**Issue by davidstosik** [gcormier/megadesk#91]
Hello there, just received and installed my Megadesk, and I'm super happy with it!

I enabled the audio feedback (memory position 17), and I like getting feedback on my button presses (the increasing pitch is genius!).

I noticed however that every now and then, the Megadesk will output a single beep, although I haven't touched it in hours. I imagine it's doing something like waking up and checking the desk position, but I was wondering if there would be a way to turn off that single beep while keeping the button press and result audio feedback?

Thanks a lot for working on this, it's great!

**Comment by gcormier** [comment]
Hey David - I'll enable my audio feedback and see if I can repro this issue.

**Comment by gcormier** [comment]
Okay, confirmed. It's very very fait and brief, just a quiet blip?

**Comment by davidstosik** [comment]
Yup, that's correct. :)

**Comment by gcormier** [comment]
I think it might be one of the audio feedback sections in linBurst(). I'll try to comment that out and see if that fixes things up.

**Comment by gcormier** [comment]
Ok flashed, I'll see how it goes :)

If it does resolve the issue you will need a programmer to update your firmware. More info : https://github.com/gcormier/megadesk/blob/master/DIY.md#programming

**Comment by davidstosik** [comment]
Yeah I thought that might be feedback in `linBurst()` too.
I probably have a programmer somewhere deep in my _stuff_, will have to take a look.
If I solder male pins, will it still fit in the case?

**Comment by gcormier** [comment]
Yes it will still fit. Alternatively you can just press and hold a 6pin header in the through holes while programming. It's how I program the units I build.

**Comment by gcormier** [comment]
I think this commit resolved it. Have you been able to flash yours to confirm?

**Comment by davidstosik** [comment]
I haven’t yet. I need to find some free time to
- solder the header
- find my programmer
- setup platformio
- compile and flash

Hopefully next weekend.

**Comment by davidstosik** [comment]
An update: I couldn't find an AVR programmer in my stuff, so I had to figure out how to use an Arduino Uno as programmer:
- [Arduino as ISP on PlatformIO's documentation](https://docs.platformio.org/en/stable/platforms/atmelavr.html#:~:text=U%20flash%3Aw%3A%24SOURCE%3Ai-,Arduino%20as%20ISP,-%5Benv%3Aprogram_via_ArduinoISP%5D%0Aplatform%20%3D%20atmelavr)
- [Arduino as ISP and Arduino Bootloaders on Arduino's docs](https://docs.arduino.cc/built-in-examples/arduino-isp/ArduinoISP)

It seems I managed to flash the board! 🎉 

Now I'll have to wait a few days and confirm whether I hear unexpected blips from Megadesk. 🤞🏻

**Comment by gcormier** [comment]
Latest release is out and fixes this.

**Comment by davidstosik** [comment]
Oh by the way, I think I haven't hear a blip since I flashed the board. 👍🏻 
Thank you!
